### ISSUE TITLE
O que a flag -u faz?

### ISSUE THREAD

**Issue by hisirdox** [theandersonn/comandos-git#13]
>Enviando as modificações para o repositório remoto
>git push origin branch

Se colocar ``git push -u origin branch ``

O que acontece?

**Comment by theandersonn** [comment]
`-u` é abreviação para `--set-upstream-to`
Configura o branch remoto como sendo upstream também. [um pouco confuso, né ?]... Tipo, o branch que está sendo usado como remoto, será setado como upstream tbm.

Leia mais aqui:
https://git-scm.com/book/en/v2/Git-Branching-Remote-Branches

Aqui eu exemplifiquei o uso do upstream:
https://github.com/theandersonn/comandos-git/blob/master/comandos/trabalhando-git-github.md

**Comment by hisirdox** [comment]
upstream?

**Comment by theandersonn** [comment]
Sim.
O uso do upstream envolve um contexto um pouquinho mais complexo, ajuda quando trabalhamos com forks.
Qual é a natureza de sua dúvida?

**Comment by hisirdox** [comment]
o que é upstream?

**Comment by theandersonn** [comment]
Explicando de maneira generalizada 'Upstream' é o nome dado a uma branch remota que irá nos auxiliar ao trabalharmos com forks... normalmente encontramos essa branch ou temos que criar essa branch, que poderia se chamar por outro nome, mas segue essa convenção.

Mas... expandindo a explicação dentro do ecossistema Git temos os conceitos de 'downstream' que é tudo que pegamos do git;  e 'upstream' que é tudo que enviamos para o git.

**Comment by hisirdox** [comment]
Obrigado.

**Comment by Pedroemanuelavelar** [comment]
O que quer dizer a flag -m do comando ```git commit -m```?

**Comment by hisirdox** [comment]
É pra indicar que você vai deixar uma mensagem no commit
