### ISSUE TITLE
Dúvida de contribuição

### ISSUE THREAD

**Issue by hugocarreira** [theandersonn/comandos-git#4]
Olá Anderson, 

Curti muito a ideia e estou afim de contribuir para ela. Usei em meu trabalho por um tempo o Git-Flow, queria saber se posso contribuir fazendo um pequeno introdução sobre ele e tal.

:)

**Comment by theandersonn** [comment]
Olá @hugocarreira, blz!?

Contribuições são bem vindas, fique a vontade; :smiley: peço a gentileza de enviar em uma nova branch.

**Comment by hugocarreira** [comment]
Fiz um commit agora!

Creio que fiz certinho..

**Comment by theandersonn** [comment]
Olhei aqui e curti!
Vi que você está fazendo algumas correções, quando finalizar dá um toque :facepunch:

**Comment by hugocarreira** [comment]
Fico feliz que curtiu.
Meu sublime limpa os espaços no final da linhas dai quebrou todas as quebras de linha.
Corrigi agora e acho que ta certo, da uma olhada e se tiver ok, fique a vontade pra fazer o PR

**Comment by theandersonn** [comment]
[Merge](https://github.com/theandersonn/comandos-git/pull/5) :+1:
